version: "3"
services:
  biblivre:
    image: claudemir1/biblivre:5.2.5-cloud
    container_name: biblivre
    restart: always
    environment: [ 'JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n',
      'DATABASE_HOST_NAME=postgres',
      'DATABASE_PORT=5432',
      'PGUSER=biblivre',
      'PGPASSWORD=abracadabra',
      'PGDATABASE=biblivre4' ]
    networks: ['postgres_default']
    ports: ['8089:8080','8009:8000']

networks:
  postgres_default:
    external: true